# -*- coding: utf-8 -*-
"""Copy of Python DA Capstone Project - Marketing Campaign Performance Insights.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RPHfh122-vktoWXvINWYu4QdVbEav-Zr

# **Marketing Campaign Performance Insights**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""## ***1) Load the Dataset***"""

df = pd.read_csv("https://raw.githubusercontent.com/ArchanaInsights/Datasets/main/marketing_campaign.csv")

"""## ***2) Descriptive Analysis***

### **Basic Structure:**
"""

df.head()

df.shape

df.info()

df.select_dtypes(include='number').columns

num_col = ['Conversion_Rate', 'Acquisition_Cost', 'ROI', 'Clicks', 'Impressions', 'Engagement_Score']
num_col

df[num_col].describe().astype(int)

"""### **Data Exploration:**"""

df['Campaign_ID'].nunique()

unique = ['Location', 'Customer_Segment']

for i in unique:
  print(f'{i} Column Unique Values: {df[i].unique()}\n')

values = ['Campaign_Type', 'Channel_Used']

for a in values:
    print(f'Column Value Count: {df[a].value_counts()}\n')

"""## ***3) Exploratory Data Analysis (EDA) and Visualization***

### **Campaign Performance:**
"""

sns.scatterplot(data=df, x='Acquisition_Cost', y='ROI')
plt.title('Acquisition Cost vs ROI')
plt.xlabel('Acquisition Cost')
plt.ylabel('ROI')
plt.show()

plt.figure(figsize=(10, 6))
sns.barplot(data=df, x='Channel_Used', y='Conversion_Rate', hue='Campaign_Type',palette='Blues')

plt.title('Average Conversion Rate by Channel and Campaign Type')
plt.xlabel('Channel Used')
plt.ylabel('Average Conversion Rate')

plt.xticks(rotation=45)
plt.legend(bbox_to_anchor=(1, 1))
plt.show()

plt.figure(figsize=(10, 6))
sns.boxplot(data=df, x='Campaign_Type', y='Engagement_Score',color='royalblue')
plt.title('''Engagement Score Distribution by Campaign Type''')
plt.xlabel('Campaign Type')
plt.ylabel('Engagement Score')
plt.show()

a = sns.barplot(data=df, x='Company', y='ROI', palette='Set2')
a.bar_label(a.containers[0])
a.bar_label(a.containers[1])
a.bar_label(a.containers[2])
a.bar_label(a.containers[3])
a.bar_label(a.containers[4])
plt.title('Average ROI by Company')
plt.xlabel('Company')
plt.ylabel('Average ROI')
plt.xticks(rotation=45)
plt.show()

cor = df[['Engagement_Score','Conversion_Rate']].corr()
sns.heatmap(cor, annot=True, cmap='Blues', fmt='.2f')
plt.title('Correlation between Engagement Score and Conversion Rate')
plt.show()

"""### **Customer Segmentation:**"""

plt.figure(figsize=(10, 6))
C = sns.countplot(data=df, x='Target_Audience', palette='Set2')
C.bar_label(C.containers[0])
C.bar_label(C.containers[1])
C.bar_label(C.containers[2])
C.bar_label(C.containers[3])
C.bar_label(C.containers[4])
plt.title('Target Audience Distribution')
plt.xlabel('Target Audience')
plt.ylabel('Count')
plt.show()

sns.barplot(data=df, x='Language', y='Conversion_Rate', hue='Customer_Segment', palette='colorblind')
plt.title('Conversion Rate by Language and Customer Segment')
plt.xlabel('Language')
plt.ylabel('Average Conversion Rate')
plt.legend(bbox_to_anchor=(1, 1))
plt.show()

plt.figure(figsize=(10, 6))

sns.boxplot(data=df, x='Customer_Segment', y='Acquisition_Cost', hue='Channel_Used')
plt.title('Acquisition Cost by Customer Segment and Channel Used')
plt.xlabel('Customer Segment')
plt.ylabel('Average Acquisition Cost')
plt.legend(bbox_to_anchor=(1, 1))
plt.tight_layout()
plt.show()

g = sns.barplot(data=df, x='Language', y='Conversion_Rate')
g.bar_label(g.containers[0])
plt.title('Average Conversion Rate by Language')
plt.xlabel('Language')
plt.ylabel('Average Conversion Rate')
plt.show()

"""### **Channel Eff ectiveness:**"""

sns.barplot(data=df, x='Channel_Used', y='Engagement_Score', hue='Campaign_Type')
plt.title('Engagement Score by Channel and Campaign Type')
plt.xlabel('Engagement Score')
plt.ylabel('Channel Used')
plt.legend(bbox_to_anchor=(1, 1))
plt.show()

total = df.groupby('Channel_Used')['ROI'].sum().reset_index()
total

plt.figure(figsize=(8,8))

plt.pie(total['ROI'],
        labels=total['Channel_Used'],
        autopct='%1.2f%%',
        startangle=90,
        explode=[0,0.08,0,0,0,0],
        shadow=True,
        colors=sns.color_palette('Blues'),)
plt.title('Total ROI by Channel')
plt.show()

sns.scatterplot(data=df, x='Impressions', y='Clicks', hue='Channel_Used')
plt.title('Clicks vs Impressions by Channel')
plt.xlabel('Impressions')
plt.ylabel('Clicks')
plt.legend(bbox_to_anchor=(1, 1))
plt.show()

"""### **Time-Based Analysis:**"""

sns.histplot(data=df, x='Duration', kde=True)
plt.title('Distribution of Campaign Duration')
plt.xlabel('Duration')
plt.ylabel('Frequency')
plt.tight_layout()
plt.show()

df['Date'] = pd.to_datetime(df['Date'], format='%d-%m-%Y')

plt.figure(figsize=(10, 6))
sns.lineplot(data=df, x='Date', y='Conversion_Rate',hue='Company', marker='o')
plt.title('Conversion Rate Over Date by Company')
plt.xlabel('Date')
plt.ylabel('Conversion Rate')
plt.xticks(rotation=45)
plt.legend(bbox_to_anchor=(1, 1))

plt.tight_layout()
plt.show()

sns.lineplot(data=df, x='Date', y='Engagement_Score', marker='D')
plt.title('Engagement Score Over Date')
plt.xlabel('Date')
plt.ylabel('Engagement Score')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""### **Geographic Analysis:**"""

sns.barplot(data=df, x='Location', y='Acquisition_Cost', palette='Set2')
plt.title('Acquisition Cost by Location')
plt.xlabel('Location')
plt.ylabel('Average Acquisition Cost')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

sns.barplot(data=df, x='Location', y='Conversion_Rate', hue='Target_Audience', palette='Set3')
plt.title('Conversion Rate by Location and Target Audience')
plt.xlabel('Location')
plt.ylabel('Average Conversion Rate')
plt.xticks(rotation=45)
plt.legend(bbox_to_anchor=(1, 1))
plt.show()

loca = df.groupby('Location')['ROI'].sum().reset_index()

plt.figure(figsize=(10, 6))
plt.pie(x=loca['ROI'], labels=loca['Location'], autopct='%1.1f%%', startangle=90, colors=sns.color_palette('Blues'))
plt.title('Total ROI by Location')
plt.show()